import Head from 'next/head';
import { GetStaticProps } from 'next';
import { MDXRemote } from 'next-mdx-remote';

import { postFilePaths, MD_PATH, getMdData } from '@/lib/mdx';

import styles from '../styles/index.module.css';

const Home = ({ postFilePaths, MD_PATH, ...data }: any) => {
	console.log(data);
	return (
		<div className={styles.container}>
			<Head>
				<title>tun website</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/tuntun.jpg" />
			</Head>
			<main>
				<MDXRemote {...data.source} components={{}}/>
			</main>
		</div>
	);
};

export const getStaticProps: GetStaticProps = async () => {
	const data = await getMdData('index');
	return {
		props: {
			postFilePaths,
			MD_PATH,
			...data,
		}, // will be passed to the page component as props
	};
};

export default Home;
