import Head from 'next/head';
import { GetStaticProps } from 'next';
import { MDX, TypedWriter } from '@/components';

import { getMdData } from '@/lib/mdx';

import style from '../styles/index.module.scss';

const options = {
	strings: [
		'Hi, I am TunTun.',
		'A Web front-end developer.',
	],
	typeSpeed: 50,
	backSpeed: 30,
	loop: true,
	loopCount: Infinity,
};

const Home = ({ ...data }: any) => (
	<div className={style.container}>
		<Head>
			<meta name="description" content="Generated by create next app" />
		</Head>
		<div className={style.main}>
			<div>
				<div style={{
					fontSize: '48px',
					fontWeight: 'bold',
					margin: '0.6em 0',
				}}>Welcome!</div>
				<TypedWriter
					style={{
						whiteSpace: 'pre',
						color: 'rgb(85, 85, 85)',
						padding: '1.3em 0',
					}}
					options={options}
				></TypedWriter>
			</div>
			<MDX {...data.source}/>
		</div>
	</div>
);

export const getStaticProps: GetStaticProps = async () => {
	const data = await getMdData('index');
	return {
		props: {
			...data,
		},
	};
};

export default Home;
