import Head from 'next/head';
import { GetStaticProps } from 'next';
import { MDX } from '@/components';

import { getMdData } from '@/lib/mdx';

import style from '../styles/index.module.scss';

const Project = ({ ...data }: any) => (
	<div className={style.container}>
		<Head>
			<meta name="description" content="Generated by create next app" />
		</Head>
		<div className={style.main}>
			<MDX {...data.source}/>
		</div>
	</div>
);

export const getStaticProps: GetStaticProps = async () => {
	const data = await getMdData('project');
	return {
		props: {
			...data,
		},
	};
};

export default Project;
