import Head from 'next/head';
import { GetStaticProps } from 'next';
import { MDX, Main } from '@/components';

import { getMdData } from '@/lib/mdx';

const Project = ({ source }: { source: string }) => (
	<>
		<Head>
			<meta name="description" content="Generated by create next app" />
		</Head>
		<Main>
			<MDX source={source}/>
		</Main>
	</>
);

export const getStaticProps: GetStaticProps = async () => {
	const { source } = await getMdData('project');
	return {
		props: {
			source,
		},
	};
};

export default Project;
